### ISSUE TITLE
orangepi one problem 

### ISSUE THREAD

**Issue by asegura02** [nutki/rpi-nintendo-classic-controller#1]
Hi i'm trying to install this driver in Armbian  Orangepi_one   wich has 3  i2c port =  **i2c0 , i2c1 and i2c2** some how it won't detect i2c1 only 0 and 2  i have wired both controllers and they show up as id 52 

root@orangepione:~# i2cdetect -r 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- 52 -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --  

 root@orangepione:~# i2cdetect -r 2
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- 52 -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 

i'm not very good with programming  so what i need to change to make it work for the 2 controller 
thanks

**Comment by nutki** [comment]
Are you using the service as registered by `make install`? If so, this will always use i2c1 as this is what is available on RPi. You can test the other interfaces by specifying the -y parameter: `sudo ./i2c-classic-controller -d -y 0` for i2c0 for example.

To use multiple ports as a service the easiest way would be to set a system service for each port and specify the port parameter in the service configuration. I can provide more details if you can confirm the manual start with `-d` works for you.

**Comment by asegura02** [comment]
This is what i get 

root@RetrOrangePi:/rpi-nintendo-classic-controller# cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /rpi-nintendo-classic-controller
root@RetrOrangePi:/rpi-nintendo-classic-controller# make
[ 50%] Linking C executable i2c-classic-controller
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `read_bytes':
i2c-classic-controller.c:(.text+0xcf6): undefined reference to `i2c_smbus_write_byte'
i2c-classic-controller.c:(.text+0xd26): undefined reference to `i2c_smbus_read_byte'
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `initialize':
i2c-classic-controller.c:(.text+0xd44): undefined reference to `i2c_smbus_write_byte_data'
i2c-classic-controller.c:(.text+0xd58): undefined reference to `i2c_smbus_write_byte_data'
i2c-classic-controller.c:(.text+0xd78): undefined reference to `i2c_smbus_write_byte_data'
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `main':
i2c-classic-controller.c:(.text.startup+0x142): undefined reference to `i2c_smbus_write_byte_data'
i2c-classic-controller.c:(.text.startup+0x158): undefined reference to `i2c_smbus_write_byte_data'
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o:i2c-classic-controller.c:(.text.startup+0x178): more undefined references to `i2c_smbus_write_byte_data' follow
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `main':
i2c-classic-controller.c:(.text.startup+0x2f0): undefined reference to `i2c_smbus_write_byte'
i2c-classic-controller.c:(.text.startup+0x302): undefined reference to `i2c_smbus_read_byte'
collect2: error: ld returned 1 exit status
CMakeFiles/i2c-classic-controller.dir/build.make:94: recipe for target 'i2c-classic-controller' failed
make[2]: *** [i2c-classic-controller] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/i2c-classic-controller.dir/all' failed
make[1]: *** [CMakeFiles/i2c-classic-controller.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
root@RetrOrangePi:/rpi-nintendo-classic-controller#

**Comment by asegura02** [comment]
root@RetrOrangePi:/rpi-nintendo-classic-controller# make install
[ 50%] Linking C executable i2c-classic-controller
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `read_bytes':
i2c-classic-controller.c:(.text+0xcf6): undefined reference to `i2c_smbus_write_byte'
i2c-classic-controller.c:(.text+0xd26): undefined reference to `i2c_smbus_read_byte'
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `initialize':
i2c-classic-controller.c:(.text+0xd44): undefined reference to `i2c_smbus_write_byte_data'
i2c-classic-controller.c:(.text+0xd58): undefined reference to `i2c_smbus_write_byte_data'
i2c-classic-controller.c:(.text+0xd78): undefined reference to `i2c_smbus_write_byte_data'
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `main':
i2c-classic-controller.c:(.text.startup+0x142): undefined reference to `i2c_smbus_write_byte_data'
i2c-classic-controller.c:(.text.startup+0x158): undefined reference to `i2c_smbus_write_byte_data'
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o:i2c-classic-controller.c:(.text.startup+0x178): more undefined references to `i2c_smbus_write_byte_data' follow
CMakeFiles/i2c-classic-controller.dir/i2c-classic-controller.c.o: In function `main':
i2c-classic-controller.c:(.text.startup+0x2f0): undefined reference to `i2c_smbus_write_byte'
i2c-classic-controller.c:(.text.startup+0x302): undefined reference to `i2c_smbus_read_byte'
collect2: error: ld returned 1 exit status
CMakeFiles/i2c-classic-controller.dir/build.make:94: recipe for target 'i2c-classic-controller' failed
make[2]: *** [i2c-classic-controller] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/i2c-classic-controller.dir/all' failed
make[1]: *** [CMakeFiles/i2c-classic-controller.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
root@RetrOrangePi:/rpi-nintendo-classic-controller#

**Comment by asegura02** [comment]
root@RetrOrangePi:/rpi-nintendo-classic-controller# sudo ./i2c-classic-controller -d -y 0
sudo: ./i2c-classic-controller: command not found
root@RetrOrangePi:/rpi-nintendo-classic-controller#

**Comment by nutki** [comment]
From the output it is clear that the driver is not compiling properly. I think this is due to a change in i2c library. You can try adding
the line `target_link_libraries(i2c-classic-controller i2c)` at the end of CMakeLists.txt and rpeat the process starting from `cmake .`.

**Comment by nutki** [comment]
I remembered that this was reported to me on Reddit before. See my comment there https://www.reddit.com/r/RetroPie/comments/iiz1f5/nessnes_classic_mini_controller_on_raspberry_pi/gg4hdtm?utm_source=share&utm_medium=web2x&context=3

**Comment by asegura02** [comment]
Thanks Nutki ,now driver is installed 
is registering all the events  in both cases , but in retropie , Show 1 Gamepads detected, but won´t let me map the buttons


pi@RetrOrangePi:/rpi-nintendo-classic-controller$ sudo ./i2c-classic-controller -d -y 0                                                                                 
Detected device: 00 00 A4 20 01 01
buttons: 

pi@RetrOrangePi:/rpi-nintendo-classic-controller$ sudo ./i2c-classic-controller -d -y 2                                                                                
Detected device: 00 00 A4 20 01 01
buttons:

**Comment by asegura02** [comment]
Thanks Nutki ,now driver is installed
is registering all the events in both cases , but in retropie , Show 2 Gamepads detected, but won´t let me map the buttons

pi@RetrOrangePi:/rpi-nintendo-classic-controller$ sudo ./i2c-classic-controller -d -y 0
Detected device: 00 00 A4 20 01 01
buttons: B Y A X < > ^ V - + L R

pi@RetrOrangePi:/rpi-nintendo-classic-controller$ sudo ./i2c-classic-controller -d -y 2
Detected device: 00 00 A4 20 01 01
buttons: B Y A X < > ^ V - + L R

**Comment by asegura02** [comment]
if i try the jstest nothing happends  no events registered 
and only one controller gets detected  by jstest

pi@RetrOrangePi:~$ jstest /dev/input/js1
Driver version is 2.1.0.
Joystick (Nintendo I²C Controller) has 4 axes (X, Y, Rx, Ry)
and 15 buttons (BtnA, BtnB, BtnX, BtnY, BtnTL, BtnTR, BtnTL2, BtnTR2, BtnSelect, BtnStart, BtnMode, (null), (null), (null), (null)).
Testing ... (interrupt to exit)
Axes:  0:     0  1:     0  2:     0  3:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off 11:off 12:off 13:off 14:off

**Comment by nutki** [comment]
Is the debug mode printing the output as you pasted including all characters at the same time: `buttons: B Y A X < > ^ V - + L R`?
It should only print the ones currently pressed. If you indeed see them all at the same then it could be a fault in communication (though something is working as the pad returned a valid ID sequence: 00 00 A4 20 01 01).

Also note that the driver process needs to be running for any other software to detect the pads. If you did the default installation without modification to the service script then it will start a service for i2c-1 which you don't use. To start the driver manually without a service you can do `sudo ./i2c-classic-controller -y 0 &` from the console (it will run in the background until the system restarts, so remember to kill it before starting another one on the same port or they will certainly conflict).

**Comment by asegura02** [comment]
buttons: B Y A X < > ^ V - + L R is printing one button at the at the time , i ran sudo ./i2c-classic-controller -y 0 and now runs in retropie  but not in the games , i will keep testing , is there a way to get both ports  i2c0 & i2c2 running  at the same time?
i really don't know how to change the service for i2c-0 by default were i need to edit the script value ?

thanks for your help

**Comment by nutki** [comment]
The only way to handle both ports at the same time is to run two instances of the driver.
To auto start the driver on ports 0 and 2 edit the file `/etc/systemd/system/nintendo-i2c-controller.service` to include the parameter `-y 0` in the `ExecStart` line. Then make a copy under, for example, `/etc/systemd/system/nintendo-i2c-2-controller.service` and change the parameter to `-y 2` (maybe also modify the description in the fist line, not sure if it has to be unique per service).

I considered writing the driver to handle multiple ports, but given that I could not test it on the RPi anyway (could not get the controllers to work on software emulated i2c ports so only had one port available) and the overhead of running two processes is minimal, I did not pursue this.

**Comment by asegura02** [comment]
it worked like you said  i made 2 services files nintendo-i2c-controller.service  &  nintendo-i2c-controller2.service , one file   with  -y 0  and  the other with  -y 2   , now is working fine  , both controllers and inside the games there no problem, thanks for your support

**Comment by nutki** [comment]
Thanks for reporting, the compilation issue you originally had is now fixed in my recent change.
